# Build targets for Toucan keyboard
# Usage: just build all | just build toucan | just build toucan_left
---
include:
  # Left half with Nice View display + ZMK Studio
  - board: xiao_ble
    shield: toucan_left nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: "-DCONFIG_ZMK_STUDIO=y"
    artifact-name: toucan_left

  # Right half with Cirque trackpad
  - board: xiao_ble
    shield: toucan_right
    artifact-name: toucan_right
